Pike as required dependence on MPI so decare it (PHI Kanban #3693)
If you try to build PIKE in serial, you get:

pike/blackbox/src/Pike_MultiphysicsDistributor.cpp:4:17: fatal error: mpi.h: No such file or directory

 #include "mpi.h"

Therefore, I have make MPI required.